-- =============================================================
-- RBAC System Tables
-- Multi-tenant: scoped by program_code
-- =============================================================

CREATE TABLE IF NOT EXISTS sys_user (
    id              BIGSERIAL       PRIMARY KEY,
    username        VARCHAR(64)     NOT NULL,
    password_hash   VARCHAR(256)    NOT NULL,
    real_name       VARCHAR(128),
    email           VARCHAR(256),
    phone           VARCHAR(32),
    platform_role   VARCHAR(32)     NOT NULL DEFAULT 'OPERATOR',
    status          VARCHAR(16)     NOT NULL DEFAULT 'ACTIVE',
    program_code    VARCHAR(64)     NOT NULL,
    last_login_at   TIMESTAMPTZ,
    created_at      TIMESTAMPTZ     DEFAULT NOW(),
    updated_at      TIMESTAMPTZ,
    UNIQUE(program_code, username)
);
CREATE INDEX IF NOT EXISTS idx_sys_user_program ON sys_user(program_code);

CREATE TABLE IF NOT EXISTS sys_role (
    id              BIGSERIAL       PRIMARY KEY,
    role_name       VARCHAR(128)    NOT NULL,
    role_code       VARCHAR(64)     NOT NULL,
    description     VARCHAR(512),
    data_scope      VARCHAR(16)     DEFAULT 'TENANT',
    is_system       BOOLEAN         DEFAULT FALSE,
    program_code    VARCHAR(64)     NOT NULL,
    created_at      TIMESTAMPTZ     DEFAULT NOW(),
    updated_at      TIMESTAMPTZ,
    UNIQUE(program_code, role_code)
);
CREATE INDEX IF NOT EXISTS idx_sys_role_program ON sys_role(program_code);

CREATE TABLE IF NOT EXISTS sys_user_role (
    id              BIGSERIAL       PRIMARY KEY,
    user_id         BIGINT          NOT NULL REFERENCES sys_user(id) ON DELETE CASCADE,
    role_id         BIGINT          NOT NULL REFERENCES sys_role(id) ON DELETE CASCADE,
    UNIQUE(user_id, role_id)
);
CREATE INDEX IF NOT EXISTS idx_sur_user ON sys_user_role(user_id);
CREATE INDEX IF NOT EXISTS idx_sur_role ON sys_user_role(role_id);

CREATE TABLE IF NOT EXISTS sys_role_permission (
    id              BIGSERIAL       PRIMARY KEY,
    role_id         BIGINT          NOT NULL REFERENCES sys_role(id) ON DELETE CASCADE,
    permission_code VARCHAR(128)    NOT NULL,
    UNIQUE(role_id, permission_code)
);
CREATE INDEX IF NOT EXISTS idx_srp_role ON sys_role_permission(role_id);

-- Seed data is handled by RbacDataInitializer on first startup
-- to ensure bcrypt hashes are generated by the same library that verifies them.
